apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: dispatch
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: dispatch
    tier: frontend
